new keycloak can one middleware
mariovalney/laravel-keycloak-web-guard pull request #87
Opened 2022-11-01 16:06 UTC by andrex47

new keycloak can one middleware

2022-11-01 20:57 UTC, mariovalney requested changes

2022-11-01 20:57 UTC, mariovalney commented on src/Middleware/KeycloakCanOne.php
> +        foreach ($guards AS $guard)
```suggestion
        foreach ($guards AS $guard) {
```

2022-11-01 20:57 UTC, mariovalney commented on src/Middleware/KeycloakCanOne.php
> +        foreach ($guards AS $guard)
```suggestion
        foreach ($guards AS $guard) {
```

2022-11-01 20:59 UTC, merged

2023-04-11 16:12 UTC, mikeias-silva commented
Olá @mariovalney, poderia fazer release deste commit por favor, vai ajudar muito no projeto que estou desenvolvendo para Universidade estadual de ponta grossa.

2023-04-19 01:27 UTC, mariovalney commented
Olá @mikeias-silva ! Tudo bem?
Estou um pouco sem tempo ultimamente, mas vou tentar fazer a release essa semana.

- Chegou a testar essa versão da master?
- Qual versão do Laravel está usando?

2023-04-19 13:12 UTC, mikeias-silva commented
- sobre a versão da master, testamos sim e não funcionou;

- Aqui estamos no laravel 9.52.5

2023-04-19 19:33 UTC, mikeias-silva commented
@mariovalney, testamos a versão do André e funcionou